# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "3rd year PhD student at CNES 🚀 (French Space Agency) & IGN 🏙️🌳 (French Mapping Agency) " # the website title (if blank, full name will be used instead)
first_name: "Camille"
middle_name:
last_name: "Billouard"
email: "camillebillouard314@gmail.com"
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Personal website of Camille Billouard, PhD candidate in 3D computer vision
  and neural rendering for satellite imagery at CNES, in collaboration with
  IGN/LASTIG and Univ Gustave Eiffel.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank" rel="external nofollow noopener">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio" target="_blank" rel="external nofollow noopener">al-folio</a> theme.

icon: 🧠 # the emoji used as the favicon
keywords: computer vision, neural radiance fields, NeRF, LiDAR, 3D reconstruction, remote sensing, deep learning, PhD

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon_html: <i class="fa-solid fa-cube"></i> # if you want to use an icon instead of an emoji

# -----------------------------------------------------------------------------
# Server
# -----------------------------------------------------------------------------

url: https://ellimac0.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/. Leave empty for root.
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# Light/dark mode default
default_mode: "auto" # "light", "dark", or "auto"

# Repository (used to link to your GitHub)
repo: Ellimac0/Ellimac0.github.io

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links and images when posts are shared on social media.
# Set to true and your site will include OG and Schema.org metadata for sharing.
serve_og_meta: true
serve_schema_org: true
og_image: # The site-wide (default) OG image, displayed when sharing the home page.

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: Ellimac0 # your GitHub user name
gitlab_username: # your GitLab user name
twitter_username: # your X handle
mastodon_username: # your fediverse address, e.g. example@mastodon.social
linkedin_username: # your LinkedIn user name (the part after /in/)
scholar_userid: # your Google Scholar ID (found in the URL of your Scholar profile)
semanticscholar_id: # your Semantic Scholar ID
whatsapp_number: # your WhatsApp number (full phone number in international format. Omit any zeroes, brackets, or dashes when adding the phone number in international format.)
orcid_id: # your ORCID ID (without the URL)
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
work_url: # work page URL
youtube_id: # YouTube channel id, e.g. UCfXTOXuhInIBSf3i_5C-uTQ
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
wikipedia_id: # your wikipedia id (Case sensitive)
strava_userid: # your strava userid
stackoverflow_id: # your stackoverflow id
kaggle_id: # your kaggle id
lastfm_id: # your lastfm id
spotify_id: # your spotify id
pinterest_id: # your pinterest id
unsplash_id: # your unsplash id
instagram_id: # your instagram id
facebook_id: # your facebook id
discord_id: # your discord id (18-digit unique numerical identifier)
zotero_username: # your zotero user id (string of integers)
osf_id: # your OSF id, hex string of length 5 or 24, found in the URL of your profile, e.g. 12ab3 for https://osf.io/12ab3/
google_analytics: # your Google Analytics tracking ID (format: G-XXXXXXXXXX)

contact_note: >
  Best way to reach me is via email.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: blog
blog_description: thoughts, notes, and research log
permalink: /blog/:year/:title/
lsi: false # produce an index for related posts

# Pagination
pagination:
  enabled: true

# Comments
disqus_shortname: # put your disqus shortname
giscus:
  repo: # <github-username>/<github-repo>

# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5
news_scrollable: true # adds a vertical scroll bar if there are more than 3 news items
news_move_to_top_date: # date in the future to move news to the top of the page

# Collections
announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the same page

latest_posts:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts

selected_papers: true # includes a list of papers marked as "selected={true}"

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: ["[Nom]"]
  first_name: ["[Prénom]", "[P.]"]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocesses your bibtex to allow MathJax to render the equations.

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  group_by: year
  group_order: descending

  bibtex_filters: [latex, smallcaps, superscript]

  show_bibtex_button: true
  show_abstract_button: true
  show_diff_badge_button: true # show "diff" button to compare bib changes
  show_thumbnail: true # show thumbnail of paper to the left of the title

enable_publication_thumbnails: true # publication thumbnails (images)
enable_publication_badges:
  altmetric: false # citation badge from altmetric.com
  dimensions: false # citation badge from dimensions.ai
  google_scholar: false # citation badge from Google Scholar
  inspirehep: false # citation badge from inspirehep.net
  isidore: false # citation badge from isidore.science
  semanticscholar: false # citation badge from semanticscholar.org

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preview, altmetric, dimensions, google_scholar_id, video, additional_info, annotation, editor, journal_abbr, isidore, inspirehep_id, semanticscholar]

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-resize-only 800x480>"

# -----------------------------------------------------------------------------
# Jekyll Diff
# -----------------------------------------------------------------------------

jekyll_diff:
  hide: false # automatically hide diff badges for unchanged entries

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false # enables google analytics
enable_panelbear_analytics: false # enables panelbear analytics
enable_google_verification: false # enables google site verification
enable_bing_verification: false # enables bing site verification
enable_masonry: true # enables automatic project cards arrangement
enable_math: true # enables MathJax
enable_tooltips: false # enables tooltips by default for citations and abbreviations
enable_darkmode: true # enables switching between light/dark modes
enable_navbar_social: false # enables social icons in the navbar
enable_project_categories: true # enables categorization of projects into multiple categories
enable_medium_zoom: true # enables image zoom feature (as on medium.com)
enable_progressbar: true # enables a horizontal progress bar linked to scroll position
enable_video_embed: true # enables video embedding (e.g., YouTube videos)

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI="
fontawesome:
  version: "6.5.1"
  integrity: "sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
popper:
  version: "2.11.2"
  integrity: "sha256-pS96pU17yq+gVu4KBQJi78n4GG3PIw9wRSjP+CqxjUU="
medium_zoom:
  version: "1.0.6"
  integrity: "sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM="
