name: Prettier code formatter
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: # permet de lancer manuellement depuis l'onglet Actions
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write # nécessaire pour push le commit de formatage
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Run Prettier --write ✍️
        run: npx prettier . --write
      - name: Commit changes if any 📦
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "style: apply Prettier formatting"
            git push
          else
            echo "No formatting changes needed."
          fi
